// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MssqlQuery(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['MssqlQuery'](arg1, arg2, arg3, arg4, arg5);
}

export function PostgresGetDatabases(arg1, arg2, arg3) {
  return window['go']['main']['App']['PostgresGetDatabases'](arg1, arg2, arg3);
}

export function PostgresQuery(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PostgresQuery'](arg1, arg2, arg3, arg4, arg5);
}
