name: test

on:
  # manual triggering (with [name] input)
  workflow_dispatch:
    inputs:
      name:
        description: 'Release Name'
        required: true
        default: 'New release'

  # automatic trigger when a version tag is pushed
  push:
    tags:
      - "v*.*.*"

env:
  # Build output filename without the extension
  TEST1: var-1

jobs:

  build-and-publish:
    name: test
    runs-on: windows-latest

    steps:
      - name: test2
        run: |
            echo "TEST2=var-2-${{ env.TEST1 }}\${{ env.TEST1 }}--${env:TEST1}" >> $GITHUB_ENV
            echo $TEST2
            echo $GITHUB_ENV

      - name: test3-bash
        run: |
            echo "TEST3=var-3-${{ env.TEST1 }}\${{ env.TEST1 }}" >> $GITHUB_ENV
            echo $TEST3
            echo $GITHUB_ENV
        shell: bash
        

      - name: echo1
        run: |
            echo "$TEST2"
            echo "$TEST3"
            echo "${{ env.TEST2 }}"
            echo "${{ env.TEST3 }}"
            echo "${env:TEST2}"
            echo "${env:TEST3}"
            echo "$GITHUB_ENV"

      - name: echo2
        run: echo "$TEST3"

      - name: echo4
        run: echo "$GITHUB_ENV"

      - name: release1
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ inputs.name }}1

      - name: release2
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ inputs.name }}2
          tag_name: test-tag
