name: test

on:
  # manual triggering (with [name] input)
  workflow_dispatch:
    inputs:
      name:
        description: 'Release Name'
        required: true
        default: 'New release'

  # automatic trigger when a version tag is pushed
  push:
    tags:
      - "v*.*.*"

env:
  # Build output filename without the extension
  TEST1: var-1

jobs:

  build-and-publish:
    name: test
    runs-on: windows-latest

    permissions:
        contents: write

    steps:
      - name: test2
        run: |
            echo "TEST2=var-2-${{ env.TEST1 }}\${{ env.TEST1 }}--${env:TEST1}" >> $GITHUB_ENV
            echo $TEST2
            echo $GITHUB_ENV

      - name: test3-bash
        run: |
            echo "TEST3=var-3-${{ env.TEST1 }}\${{ env.TEST1 }}" >> $GITHUB_ENV
            echo $TEST3
            echo $GITHUB_ENV
        shell: bash
        

      - name: echo1
        run: echo "$GITHUB_CONTEXT"
        shell: bash

      - name: echo ref
        run: echo "${{ github.ref }} - ${{ github.ref_type }}"
        shell: bash

      - name: echo2
        run: echo "$TEST3 ${{ env.TEST3 }}"


      - name: release1
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ inputs.name }}
          tag_name: ${{ inputs.name }}
